# Generated by Django 5.2.4 on 2025-07-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('type', models.CharField(choices=[('YOGA', 'Yoga'), ('ZUMBA', 'Zumba'), ('HIIT', 'Hiit')], max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.CharField(max_length=300, null=True)),
                ('slot', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=300, null=True)),
                ('client_email', models.EmailField(max_length=200, null=True)),
                ('fitness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitness', to='omnifyApp.fitness')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
